### ISSUE TITLE
Layout and Designs

### ISSUE THREAD

**Issue by joshuadabejero** [gnovator/gnovator.github.io#1]
#### Task(s):

- [ ] Home Page Layout - `/_layouts/home.html`.
- [ ] Add a <div></div> empty block for navigation bar.
- [ ] Add a Carousel (use any image to render from [Pexels](pexels.com))

#### Task(s):
- [ ] Add or edit a Page Layout - `/_layouts/page.html` a global page layout for all common pages.
- [ ] Add a <div></div> empty block for navigation bar.
